Capstone1 Holistic Med Summit
Nyame-Wolf/Frontend-Global-Meetup pull request #1
Opened 2022-06-23 22:13 UTC by Nyame-Wolf

In this pull request:
- I created responsive  home and about pages, for mobile and desktop following Cindy Shin's design on behance
-  I activated the mobile menu hamburger menu to open once click and close once the x button is clicked. Once a menu item is clicked, user is redirected to the place one is interested in.
- I updated my readme to describe the capstone project as well as acknowledge the designer.
- I recored a video describing my project. The [link is]()

2022-06-23 23:03 UTC, MahmoudBakr23 requested changes
Hello @Nyame-Wolf  😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Great design following so far
- Well done writing your README
- Great presentation
- Correct Linters
- Descriptive PR and commit messages
- Great semantically written HTML

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 23:03 UTC, MahmoudBakr23 commented on about.html
> +      </footer>
- [ ] Please make sure to make the footer on the about page match the original design, logo on the left, and text on the right
_Your design_
![footer about](https://user-images.githubusercontent.com/47625407/175427488-5a8fd6e2-c55c-4ace-8739-4f77cd2215e1.png)

2022-06-23 23:03 UTC, MahmoudBakr23 commented on about.html
> +      </section>
- [ ] Please make sure to align your elements to match the original design in the main section of the about page.
_Your design_
![about](https://user-images.githubusercontent.com/47625407/175427665-a34b5f88-6e73-44d9-9f21-63f403271e8f.png)

2022-06-23 23:03 UTC, MahmoudBakr23 commented on about.html
> +          <img class="summit" src="assets/summit2.png" alt="" />
- [ ] Kindly adjust these two pictures at the bottom of the about page to align like the original design shows.
_Your design_
![red pics](https://user-images.githubusercontent.com/47625407/175427913-6a119bed-b72f-4514-aef7-355cba654d93.png)

2022-06-23 23:03 UTC, MahmoudBakr23 commented on index.html
> +        <a href="index.html"><img class="logo-img" src="assets/logo-final-use.png" alt="logo"></a>
- [ ] Kindly align the logo to the left of the navbar as the original design shows
_Your design_
![navbar](https://user-images.githubusercontent.com/47625407/175428559-8eb0a852-ef01-409c-8f32-e3655f437d10.png)

2022-06-23 23:03 UTC, MahmoudBakr23 commented on index.html
> +          <p class="p1description">
- [ ] Kindly add one more card in the program section as the original design shows
_Your design_
![program](https://user-images.githubusercontent.com/47625407/175428637-a2d3edf0-ae00-495b-8082-c889f01cc627.png)

2022-06-23 23:03 UTC, MahmoudBakr23 commented on index.html
> +            rel="noopener noreferrer"><img class="open-s" src="assets/opensocietyfoundationsfitwidth.png" alt=""></a>
- [ ] Please add the dotted black and white background or something similar to the design as the original design shows
_Your design_
![speakers](https://user-images.githubusercontent.com/47625407/175428737-f5e4538b-6026-443a-bcc9-99f4c274f7a9.png)

2022-06-23 23:03 UTC, MahmoudBakr23 commented on index.html
> +          <a class="partner-link" href="https://www.opensocietyfoundations.org/" target="_blank"
- [ ] Please work on the sizes of the icons/logos in the partner's section to match the original design
_Your design_
![partners](https://user-images.githubusercontent.com/47625407/175428842-4a2916a5-eb02-49b1-a3f5-e62d24a04c0a.png)

2022-06-23 23:03 UTC, MahmoudBakr23 commented on index.html
> +      </div>
- [ ] Kindly align the elements of the footer on the home page to match the original design, the logo on the left, and the text on the right!
_Your design_
![footer home](https://user-images.githubusercontent.com/47625407/175428909-f2fa385c-0433-437e-8f8a-690128b80163.png)
n

2022-06-24 08:41 UTC, AshakaE requested changes
Hi @Nyame-Wolf  🙋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

🟡  Kindly work on the changes requested by the previeous reviewer 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 10:03 UTC, rukundoeric requested changes
Hello @Nyame-Wolf 👋,

_This is an additional review as a result of the second opinion request._

- [ ] As mentioned in the previous review, you did not address most of the issues raised in the first review. there are still few things we need to fix to make our app look more like the provided design. Kindly review the following issues and make sure to fix them.

Keep rocking 🚀!

2022-06-24 10:03 UTC, rukundoeric commented on index.html
> +        <ul class="top-bar">
- [ ] <b>REQUIRED:</b> kindly try to make sure that the orientation of your header matches with the one in provided design. 

| Original      | Yours |
  | ----------- | ----------- |
| ![Screen Shot 2022-06-24 at 11 06 44](https://user-images.githubusercontent.com/45217364/175508360-602b5e24-fb35-4a9b-984d-b2f07987113d.png) | ![Screenshot(4)](https://user-images.githubusercontent.com/45217364/175508222-a71bd075-592a-47a9-84ff-c9b3d4e319a9.png) |

2022-06-24 10:03 UTC, rukundoeric commented on index.html
> +        <div class="speakers"></div>
- [ ] <b>REQUIRED:</b> Also, here as mentioned in the previous review, Please add the dotted black and white background or something similar to the design as the original design shows. 

| Original      | Yours |
  | ----------- | ----------- |
| ![Screenshot](https://user-images.githubusercontent.com/45217364/175509615-1183c5b8-7c79-486e-9805-9c2579a40bea.png) | ![Screenshot(3)](https://user-images.githubusercontent.com/45217364/175509694-ea205b56-e665-4bd5-b525-116c91c2b30d.png) |

2022-06-24 10:03 UTC, rukundoeric commented on index.html
> +        <div class="fot1">
- [ ] <b>REQUIRED:</b> In the footer, Kindly make sure that the content is in the center as it in the given design.

| Original      | Yours |
  | ----------- | ----------- |
| ![Screenshot(2)](https://user-images.githubusercontent.com/45217364/175510430-4c052d4a-8572-4f94-9c91-c3176b40c665.png) | ![Screenshot(5)](https://user-images.githubusercontent.com/45217364/175510514-3f75aaca-2eb1-4f53-93aa-f83616e10990.png) |

2022-06-24 10:03 UTC, rukundoeric commented on about.html
> +          />
- [ ] <b>REQUIRED:</b> Also like mentioned in the previous review, these two pics should be aligned in the center like they are in the given design. 

| Original      | Yours |
  | ----------- | ----------- |
| ![Screenshot(8)](https://user-images.githubusercontent.com/45217364/175512894-6e0aaed7-79d2-4b63-80ac-e148b0ef2ddb.png) | ![Screenshot(7)](https://user-images.githubusercontent.com/45217364/175512215-a94093bd-52bb-46a7-b84d-f8f3fb0918ee.png) |

2022-06-24 11:26 UTC, Munsa1 approved these changes
Hi @Nyame-Wolf, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 

Optional
![image](https://user-images.githubusercontent.com/81932478/175525192-5574952c-c08b-4d6b-8354-231c72b5df22.png)
- [ ] Kindly align the items in the image above
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-06-24 11:27 UTC, merged